### ISSUE TITLE
How does it calculate the total time of a segment in a parallel manner?

### ISSUE THREAD

**Issue by LilAiTT** [stanford-mast/nn_dataflow#24]
Here is the code in the Class NNDataflowScheme(./core/nn_dataflow_scheme.py)
`
        
        self.sum_cost = 0 # Naive sum of all layer cost.
        self.sum_static_cost = 0
        
        self.sum_time = 0 # Naive sum of all layer time, used to adjust cost.
`
It seems like the total time of a segment is merely adding up the time consuming of each layer. I can't find the code about pipelining in a segment.
Do I miss something? If it is, could you please point out which the code is about pipelining the layers in a segment?

**Comment by gaomy3832** [comment]
As the comment says, `sum_time` is just a native sum of all layer time, only used in `total_cost()` to adjust the static cost. The actual overall time is `total_time()` (as it is marked as a property, you can simply access it as `self.total_time` rather than `self.total_time()`).  And as https://github.com/stanford-mast/nn_dataflow/blob/198a5274b9529125c6aa2b8b72b365d60cf83778/nn_dataflow/core/nn_dataflow_scheme.py#L175 shows, the total time is the sum of all segments' time. And the actual calculation of the segment time is in `core/pipeline_segment_timing.py`.

**Comment by LilAiTT** [comment]
Thank you, that helps a lot!
Closing the question!
