### ISSUE TITLE
Are SPADs in the PE also double-buffered?

### ISSUE THREAD

**Issue by hex0102** [stanford-mast/nn_dataflow#7]
Hi,

In the simulation, are SPADs in the PE also double-buffered?
I just started looking at the codes for Eyeriss, it seems like you set the regf as  ' size_regf=261,  # (225 + 12 + 24)'. 
In the paper, it's 12*16b+224*16b+24*16b which is two times larger.
Also, it seems like the total of ifmap, filter, psum is 224+12+24 =260.
Could you help to clarify a little bit?
Thank you.

**Comment by gaomy3832** [comment]
It seems you are referring to [this line](https://github.com/stanford-mast/nn_dataflow/blob/v1.5/nn_dataflow/tests/dataflow_test/test_nn_dataflow.py#L256).

No, neither the regf nor the gbuf in this tool is double buffered. The problem is the units of the numbers.

From the command line, when you invoke `nn_dataflow/tools/nn_dataflow_search.py`, the command line options `--regf` and `--gbuf` use bytes, as people expect.

Inside the source file, when you initiate an instance of `Resource`, the fields `size_regf` and `size_gbuf` use data elements as their units. This makes it easier to uniformly support different data width. The translation is done within `nn_dataflow/tools/nn_dataflow_search.py`.

In your case, the regf size should be around 512 bytes with 16-bit data, so it is about 256 elements. The `// 2` in the line of `size_gbuf` right above is also due to the same reason, not because of double-buffering.
